name: Build manifest.json

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate manifest.json
        run: |
          echo "Generating manifest.json..."
          MANIFEST_PATH="manifest.json"
          echo "{\"version\":\"0.1.0\",\"files\":[]}" > $MANIFEST_PATH

      - name: Commit manifest.json
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add manifest.json
          git commit -m "Auto-generate manifest.json" || echo "No changes to commit"
          git push
